version: '3'
services:
  web:
    container_name: web-node-prototype
    build:
      context: .
      dockerfile: ./infrastructure/docker/${NODE_ENV}/Dockerfile
    ports:
      - "${PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}