version: '3'
services:
  dev:
    container_name: dev-node-prototype
    build:
      context: .
      dockerfile: ./docker/${NODE_ENV}/Dockerfile
    ports:
      - "${PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
  prod:
    container_name: prod-node-prototype
    build:
      context: .
      dockerfile: ./docker/${NODE_ENV}/Dockerfile
    ports:
      - "${PORT}:3000"
    environment: 
      - NODE_ENV=${NODE_ENV}
